apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: ignite
  name: ignite
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: ignite-viewer
  namespace: ignite
spec:
  selector:
    matchLabels:
      app: ignite-viewer
  replicas: 5 
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ignite-viewer
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: ignite-viewer
        image: syngopredevelopmentimages.azurecr.io/igniteviewer:3.0
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 800m
          requests:
            cpu: 200m
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: ignite-viewer
  namespace: ignite
spec:
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 32410
      port: 80
      targetPort: 80
  selector:
    app: ignite-viewer